import { useEffect,useState } from 'react';
import { ArrowDown,ArrowUpRight,ChevronDown,Plus } from 'lucide-react';
import { Link } from 'wouter';
import { ButtonLink,Eyebrow,PageFrame,Reveal } from '../components/SiteShell';
import { faqs,projects,services,testimonials } from '../data/site';
const slides=['/assets/hero-slide-1.webp','/assets/hero-slide-2.webp','/assets/hero-slide-3.webp','/assets/hero-slide-4.webp'];
export default function Home(){const [slide,setSlide]=useState(0);const [faq,setFaq]=useState<number|null>(0);const [testimonial,setTestimonial]=useState(0);useEffect(()=>{const t=window.setInterval(()=>setSlide(v=>(v+1)%slides.length),3800);return()=>window.clearInterval(t)},[]);return <PageFrame><main className="mark-main">
<section className="poster-hero"><div className="mark-wrap poster-grid"><div><Reveal><p className="poster-index">A—001 / Digital designer</p></Reveal><Reveal><h1>Make<br/><span>noise</span><br/>useful.</h1></Reveal><Reveal><p className="poster-intro">A small independent studio for large ideas, awkward problems, and digital experiences with a pulse.</p></Reveal><Reveal className="poster-actions"><ButtonLink href="#work">View the archive</ButtonLink><a className="scroll-cue" href="#about">Keep going <ArrowDown size={15}/></a></Reveal></div><div className="poster-visual"><div className="poster-image" key={slide}><img src={slides[slide]} alt="Waleed design work"/><span className="poster-sticker">PLAY<br/>WITH<br/>IDEAS</span><span className="poster-slide">0{slide+1}<i>/04</i></span></div><p>Visual note / rotating every few seconds</p></div></div><div className="poster-edge">DESIGN FOR HUMANS <b>↗</b> DESIGN FOR HUMANS <b>↗</b> DESIGN FOR HUMANS</div></section>
<section className="intro-band" id="about"><div className="mark-wrap intro-band-grid"><Reveal><Eyebrow>About the practice</Eyebrow></Reveal><Reveal><h2>Not here to add<br/>more. Here to add<br/><i>meaning.</i></h2><p>Brand identities, product experiences, and websites that earn attention by being clear, useful, and a little unexpected.</p><div className="intro-tags"><span>01 / Strategy</span><span>02 / Design</span><span>03 / Development</span></div></Reveal></div></section>
<section className="archive-section" id="work"><div className="mark-wrap"><div className="archive-header"><Reveal><Eyebrow>Selected archive</Eyebrow></Reveal><Reveal><h2>Things I’ve<br/><i>helped happen.</i></h2></Reveal></div><div className="archive-grid">{projects.slice(0,6).map((project,i)=><Reveal className={`archive-card archive-${i+1}`} key={project.slug}><Link href={`/project/${project.slug}`}><div className="archive-media" style={{backgroundColor:project.accent}}><img src={project.image} alt={`${project.name} project preview`} loading={i>1?'lazy':'eager'}/><span>0{i+1}</span><b><ArrowUpRight size={17}/></b></div><div className="archive-meta"><h3>{project.name}</h3><p>{project.category} <em>—</em> {project.year}</p></div></Link></Reveal>)}</div></div></section>
<section className="practice-section" id="practice"><div className="mark-wrap"><div className="practice-top"><Eyebrow>What happens here</Eyebrow><p>Different tools.<br/>Same intention.</p></div><div className="practice-list">{services.map(service=><Link href={`/service/${service.slug}`} key={service.slug}><span>{service.number}</span><h3>{service.title}</h3><p>{service.short}</p><ArrowUpRight size={18}/></Link>)}</div></div></section>
<section className="manifesto-section"><div className="mark-wrap manifesto"><span className="manifesto-symbol">✳</span><Eyebrow>Manifesto / 04</Eyebrow><h2>Clarity is<br/>a creative<br/><i>act.</i></h2><p>Every good interface is an invitation: come closer, understand something, take the next step.</p></div></section>
<section className="portrait-section"><div className="mark-wrap portrait-grid"><div className="portrait-photo"><img src="/assets/waleed-here-768x879.webp" alt="Waleed, independent designer"/><span>Waleed<br/>/ 2026</span></div><div><Eyebrow>A little context</Eyebrow><h2>Good work<br/>needs a<br/><i>human.</i></h2><p>I like useful conversations, clear decisions, and the moment a rough idea starts to feel inevitable. I bring the same curiosity to a one-day sprint and a six-month build.</p><a className="inline-arrow" href="mailto:hiserveekay@gmail.com">Say hello <ArrowUpRight size={16}/></a></div></div></section>
<section className="words-section"><div className="mark-wrap words-grid"><Reveal><Eyebrow>People I’ve worked with</Eyebrow><div className="words-nav"><button onClick={()=>setTestimonial((testimonial+testimonials.length-1)%testimonials.length)}>←</button><span>0{testimonial+1} / 0{testimonials.length}</span><button onClick={()=>setTestimonial((testimonial+1)%testimonials.length)}>→</button></div></Reveal><Reveal><blockquote>“{testimonials[testimonial].quote}”</blockquote><p>{testimonials[testimonial].name} / {testimonials[testimonial].role}</p></Reveal></div></section>
<section className="questions-section"><div className="mark-wrap questions-grid"><div><Eyebrow>Before we start</Eyebrow><h2>Questions are<br/><i>good.</i></h2></div><div className="questions-list">{faqs.map(([q,a],i)=><div className={faq===i?'question open':'question'} key={q}><button onClick={()=>setFaq(faq===i?null:i)}>{q}{faq===i?<ChevronDown size={18}/>:<Plus size={18}/>}</button><div><p>{a}</p></div></div>)}</div></div></section>
</main></PageFrame>}
